### PR TITLE
Add zerologger plugin

### PR DESCRIPTION
**Pull request by hirosassa**
This PR added [zerolog](https://github.com/rs/zerolog) plugin.

Most of the implementations are copied from zaplogger plugin.
Since above, I did not implement example related things.

Please let me know if I miss anything. Thanks!

### CODE REVIEW

**Comment by raphael** [comment]
This is great, thank you! The only thing that popped up was the fact that the `With().Timestamp()` option is hard coded. That might be fine but another approach could be to make it possible to pass options to the logger constructor so that users can configure that. I guess that could be done later if people ask.

**Comment by raphael** [comment]
Great, is this ready to be merged?

**Comment by hirosassa** [comment]
Sorry for late reply. Just a moment, please. I want to check little bit more.

**Comment by hirosassa** [comment]
@raphael Sorry for keep you waiting. Ready to be merged!

**Comment by hirosassa** [comment]
Ping? @raphael

**Comment by raphael** [comment]
Sorry missed the initial message. Thank you!

**Comment by hirosassa** [comment]
Thank you!

**Pull request merged**
