### PR TITLE
goakit: Name services in import paths consistently with goa 

### LINKED ISSUE #116: goakit: Service import paths inconsistent with goa
The goa `codegen` consistently uses snake_case of the `service.Data.VarName` in package paths (both in file system and imports), e.g.: https://github.com/goadesign/goa/blob/v3.5.4/http/codegen/client.go#L32 and https://github.com/goadesign/goa/blob/v3.5.4/http/codegen/server.go#L34

The `goakit` plugin, on the other hand, uses snake_cased `expr.HTTPServiceExpr.Name()` in generated file system paths, but `service.Data.Name` verbatim when importing, e.g.: https://github.com/goadesign/plugins/blob/8db24fb7db9e55f83abccbba878dc322fae76681/goakit/encode_decode_files.go#L28 and https://github.com/goadesign/plugins/blob/8db24fb7db9e55f83abccbba878dc322fae76681/goakit/encode_decode_files.go#L39

This breaks the imports in the generated `kitserver`/`kitclient` packages when service names are camelCased (or even simply Capitalized).

## Repro

1. <details><summary>Implement a simple spec with a camelCased service name, e.g.:</summary>

	```golang
	package design

	import (
		. "goa.design/goa/v3/dsl"
		_ "goa.design/plugins/v3/goakit"
	)

	var _ = Service("SimpleService", func() {
		Method("SimpleMethod", func() {
			HTTP(func() {
				GET("/")
			})
		})
	})
	```

	</details>

2. <details><summary>Generate implementation (packages and CLI commands)</summary>

	```shell
	$ goa gen foo/design && \
	  goa example foo/design
	```

	</details>

### What was expected

- `foo/gen/http/simple_service/kitclient` should import `foo/gen/http/simple_service/client`
- `foo/gen/http/simple_service/kitserver` should import `foo/gen/http/simple_service/server`
- `cmd/simple_service/http.go` should import `foo/gen/http/simple_service/kitserver`

### What happens instead

- <details><summary>The <code>kitclient</code> imports <code>foo/gen/http/SimpleService/client</code></summary>

	```golang
	// ... snip ...

	package client

	import (
		"context"
		"foo/gen/http/SimpleService/client"
		"net/http"

		// ... snip ...
	)

	// ... snip ...
	```

	</details>
- <details><summary>The <code>kitserver</code> imports <code>foo/gen/http/SimpleService/server</code></summary>

	```golang
	// ... snip ...

	package server

	import (
		"context"
		"foo/gen/http/SimpleService/server"
		"net/http"

		// ... snip ...
	)

	// ... snip ...
	```

	</details>
- <details><summary><code>cmd/simple_service/http.go</code> imports <code>foo/gen/http/SimpleService/kitserver</code></summary>

	```golang
	package main

	import (
		"context"
		"fmt"
		simpleservicekitsvr "foo/gen/http/SimpleService/kitserver"
		simpleservicesvr "foo/gen/http/simple_service/server"
		simpleservice "foo/gen/simple_service"
		// ... snip ...
	)

	// ... snip ...
	```

	</details>

## Additional details

<details><summary>The fix is simple: use <code>codegen.SnakeCase</code>d <code>service.Data.VarName</code> in all the relevant spots.</summary>

```diff
diff --git a/goakit/encode_decode_files.go b/goakit/encode_decode_files.go
index e5e6d2e..a629631 100644
--- a/goakit/encode_decode_files.go
+++ b/goakit/encode_decode_files.go
@@ -25,8 +25,9 @@ func EncodeDecodeFiles(genpkg string, root *expr.RootExpr) []*codegen.File {
 // serverEncodeDecode returns the file defining the go-kit HTTP server encoding
 // and decoding logic.
 func serverEncodeDecode(genpkg string, svc *expr.HTTPServiceExpr) *codegen.File {
-	path := filepath.Join(codegen.Gendir, "http", codegen.SnakeCase(svc.Name()), "kitserver", "encode_decode.go")
 	data := httpcodegen.HTTPServices.Get(svc.Name())
+	svcName := codegen.SnakeCase(data.Service.VarName)
+	path := filepath.Join(codegen.Gendir, "http", svcName, "kitserver", "encode_decode.go")
 	title := fmt.Sprintf("%s go-kit HTTP server encoders and decoders", svc.Name())
 	sections := []*codegen.SectionTemplate{
 		codegen.Header(title, "server", []*codegen.ImportSpec{
@@ -36,7 +37,7 @@ func serverEncodeDecode(genpkg string, svc *expr.HTTPServiceExpr) *codegen.File
 			{Path: "github.com/go-kit/kit/transport/http", Name: "kithttp"},
 			{Path: "goa.design/goa/v3", Name: "goa"},
 			{Path: "goa.design/goa/v3/http", Name: "goahttp"},
-			{Path: genpkg + "/http/" + data.Service.Name + "/server"},
+			{Path: genpkg + "/http/" + svcName + "/server"},
 		}),
 	}
 
@@ -70,9 +71,10 @@ func serverEncodeDecode(genpkg string, svc *expr.HTTPServiceExpr) *codegen.File
 // clientEncodeDecode returns the file defining the go-kit HTTP client encoding
 // and decoding logic.
 func clientEncodeDecode(genpkg string, svc *expr.HTTPServiceExpr) *codegen.File {
-	path := filepath.Join(codegen.Gendir, "http", codegen.SnakeCase(svc.Name()), "kitclient", "encode_decode.go")
-	title := fmt.Sprintf("%s go-kit HTTP client encoders and decoders", svc.Name())
 	data := httpcodegen.HTTPServices.Get(svc.Name())
+	svcName := codegen.SnakeCase(data.Service.VarName)
+	path := filepath.Join(codegen.Gendir, "http", svcName, "kitclient", "encode_decode.go")
+	title := fmt.Sprintf("%s go-kit HTTP client encoders and decoders", svc.Name())
 	sections := []*codegen.SectionTemplate{
 		codegen.Header(title, "client", []*codegen.ImportSpec{
 			{Path: "context"},
@@ -81,7 +83,7 @@ func clientEncodeDecode(genpkg string, svc *expr.HTTPServiceExpr) *codegen.File
 			{Path: "github.com/go-kit/kit/transport/http", Name: "kithttp"},
 			{Path: "goa.design/goa/v3", Name: "goa"},
 			{Path: "goa.design/goa/v3/http", Name: "goahttp"},
-			{Path: genpkg + "/http/" + data.Service.Name + "/client"},
+			{Path: genpkg + "/http/" + svcName + "/client"},
 		}),
 	}
 
diff --git a/goakit/generate.go b/goakit/generate.go
index 8406c51..319e1b5 100644
--- a/goakit/generate.go
+++ b/goakit/generate.go
@@ -106,10 +106,10 @@ func gokitifyExampleServer(genpkg string, file *codegen.File) {
 			data := s.Data.(map[string]interface{})
 			svcs := data["Services"].([]*httpcodegen.ServiceData)
 			for _, svc := range svcs {
-				pkgName := httpcodegen.HTTPServices.Get(svc.Service.Name).Service.PkgName
+				svcData := httpcodegen.HTTPServices.Get(svc.Service.Name).Service
 				codegen.AddImport(file.SectionTemplates[0], &codegen.ImportSpec{
-					Path: path.Join(genpkg, "http", svc.Service.Name, "kitserver"),
-					Name: pkgName + "kitsvr",
+					Path: path.Join(genpkg, "http", codegen.SnakeCase(svcData.VarName), "kitserver"),
+					Name: svcData.PkgName + "kitsvr",
 				})
 			}
 			s.Source = gokitServerInitT
```
</details>

Testing for it, though, seems somewhat finicky, because this behavior was never covered by tests before (obviously, that's why we have it) and there is currently no clean API path for inspecting the generated imports.

This behavior originates in #6, but I couldn't find anything in there that would explain why *should* it be done this way.

thing|version
-|-
go|go1.17.6
goa|v3.5.4
plugins|v3.5.4
platform|linux/amd64

### PR DESCRIPTION
**Pull request by antichris**
Fixes #116

### CODE REVIEW

**Comment by antichris** [comment]
It would be really great if this PR could take advantage of the changes in goadesign/goa#2988, but I suspect that would require a new release over there, before this could be merged.

**Comment by raphael** [comment]
This looks great, I am planning on releasing Goa "soon" - I'd like to fix a couple of issues that have been reported first but should be able to get to it over the coming week.

**Comment by antichris** [comment]
Cool, so, I suppose I'll just go ahead and amend that last commit of this PR right away, and, once the new tag lands in the `go.mod`, I'll mark this "ready for review" so we can get this done. Does that sound good?

**Comment by raphael** [comment]
Yes sounds great

**Comment by raphael** [comment]
Just released v3.5.5

**Comment by raphael** [comment]
This is great, thank you!

**Pull request merged**
